---
title: "Literature review for Coaseian tuna paper"
author: 
date: "01/12/2018"
output: html_document
csl: conservation-letters.csl
bibliography: Coaseian Tunas.bib

---

**Reducing marine mammal bycatch in global fisheries: An economics approach**
[@Lent2017]

*Abstract:*
The broader ecosystem impacts of fishing continue to present a challenge to scientists and resource managers around the world. Bycatch is of greatest concern for marine mammals, for which fishery bycatch and entanglement is the number one cause of direct mortality. Climate change will only add to the challenge, as marine species and fishing practices adapt to a changing environment, creating a dynamic pattern of overlap between fishing and species (both target and bycatch). Economists suggest policy instruments for reducing bycatch that move away from top-down, command-and-control measures (e.g. effort reduction, time/area closures, gear restrictions, bycatch quotas) towards an approach that creates incentives to reduce bycatch (e.g. transferable bycatch allowances, taxes, and other measures). The advantages of this flexible, incentive-oriented approach are even greater in a changing and increasingly variable environment, as regulatory measures would have to be adapted constantly to keep up with climate change. Unlike the regulatory process, individual operators in the fishery sector can make adjustments to their harvesting practices as soon as the incentives for such changes are apparent and inputs or operations can be modified. This paper explores policy measures that create economic incentives not only to reduce marine mammal bycatch, but also to increase compliance and induce technological advances by fishery operators. Economists also suggest exploration of direct economic incentives as have been used in other conservation programs, such as payments for economic services, in an approach that addresses marine mammal bycatch as part of a larger conservation strategy. Expanding the portfolio of mandatory and potentially, voluntary, measures to include novel approaches will provide a broader array of opportunities for successful stewardship of the marine environment.  


*Notes:*
Provides a great review and examples of different incentive-based approaches to reducing bycatch. Discusses problems with traditional management approaches (input/output/time and space closures)- typically result in overall lowering of effort of both target and bycatch species, instead of optimizing catch for both target and bycatch species. In contrast, incentive-based approaches can allow for flexibility, increase compliance, and incentivize cost-effective technological development. The optimal level of bycatch is the level at which the cost of the last unit of bycatch reduction equals the marginal benefit of the bycatch measures implemented. However, it is often difficult to quantify the marginal cost and marginal benefit of a bycatch reduction measure.Benefit should include both market and non-market values. The paper reviews and discusses a number of examples of incentive-based management approaches that include:  putting a price on bycatch, of both compensatory and conservatory offsets, providing a reward for reducing bycatch, cap and trade approaches, insurance and risk pools, market measures, buybacks of vessels/gears. Example of 'providing a reward for reducing bycatch' includes PES which follows 'user/beneficiary pays principle' and has been used in turtle conservation and Brazilian artisan fisheries. Also used in Mexico where government paid gillnet fishery to shut down to protect vaquita (didn't seem to go well). There are some complications in applying PES to fisheries, yet they remain a promising policy instrument.  Argues cap and trade are the most effective way to reduce bycatch using AK Pollock fishery as example. Concludes with summary that incentivizing for bycatch reduction is a logical approach (and has been successful in terrestrial conservation, AK Pollock fishery, and us groundfish fishery) but seldom used in practice bc there is a lack of knowledge or understanding of approach effectiveness, and reluctance to hand over control to fisheries, and because in general change is low and there may be uncertainty about effectiveness.  



**Ecosystem-level impacts of fisheries bycatch on marine megafauna: biodiversity conservation through mitigation, policy, economic instruments, and techinical change**
[@Squires2013]

*Abstract:*
The selectivity of fishing operations is such that despite the sustained efforts made during the last decades to reduce it, the accidental capture of living marine resources (bycatch) sometimes followed by their discarding at sea1 remains an important point of friction between fisheries and biodiversity governance systems, particularly when emblematic, endangered or particularly vulnerable species are concerned. Bycatch reduction practices have traditionally focused on command-and-control measures (e.g., time-and-area closures, effort reduction) or technology standards and associated legislative changes (e.g., mesh size, hook types, bycatch excluder devices, and mandated requirements that freeze technology in place). Incentive-based bycatch reduction practices such as use rights (e.g., Dolphin Mortality Limits, DMLs), taxes, credit schemes, or insurance, may more directly and cost-effectively reduce bycatch. This approach has received insufficient attention.
In addition, conventional bycatch reduction approaches give insufficient attention to the holistic (ecosystem-level) impacts of bycatch. Bycatch reduction simply focused on at-sea catch ignores opportunities offered by more cost- and ecologically-effective bycatch mitigation measures that may directly and more effectively increase impacted populations elsewhere in their geographic range or life cycle. Finally, at-sea bycatch reduction runs the danger of obtaining increasingly smaller increments in bycatch reduction at increasingly larger increments in costs (i.e. marginal costs) to the point where additional gains in bycatch reduction are outweighed by additional costs of bycatch reduction leading to a net loss in economic benefits. A net loss in economic benefits can also lead to a net loss in biodiversity and ecological benefits if the foregone economic benefits preclude conserving biodiversity at some other point in the holistic process, i.e. there can be an opportunity cost to at-sea bycatch reduction within a broad-based and holistic bycatch perspective. A broader-based ecosystem approach to biodiversity conservation thus allows incorporating a broader range of policy instruments, applied at life stages and geographical ranges other than those of the strict harvesting process to achieve better cost- and ecological effectiveness.
One of the most important forces reducing bycatch is technical change. Examples include for tuna purse seine fisheries the backdown procedure and Medina panel that reduce dolphin bycatch or current development of ecological Fish Aggregating Devices (FADs), and for pelagic longline swordfish fisheries circle hooks and mackerel type bait that reduce sea turtle bycatch and post-hooking mortality.. However, many conventional policy instruments, such as catch rights, time and area closures or effort reduction, even when aimed at bycatch reduction, are insufficient to cover all species, do not directly create desired economic incentives, are not cost-effective because they unnecessarily reduce profitable fishing opportunities that can help finance less expensive and more effective conservation elsewhere, and limit vessel flexibility to efficiently respond to changes in market, environmental, technological, or ecological conditions.
The challenge is to develop a portfolio of bycatch management instruments that not only directly reduce bycatch, but also create incentives to stimulate and direct bycatch-saving technical change. A related question is the impact of alternative mixes of bycatch-reducing instruments, since invariably multiple instruments are imposed.
Biodiversity mitigation (offsets) is part of a holistic approach addressing all phases of a species’ life history throughout its geographic range and that provides the lowest risk, least-cost approach to conservation. It is not necessarily intended to offset current fishing or to substitute for current at-sea and other bycatch-reducing measures. Instead, it is intended to complement existing activities to provide a holistic conservation strategy that is least-cost and addresses species conservation over the entire geographical range and life history of species. As part of a comprehensive bycatch reduction conservation strategy, biodiversity mitigation enables consumers, processors, traders and brokers, and fishers to continue their activities and generate sufficient economic surplus to finance the mitigation that leads to population increases, not simply no net loss. This approach recognizes that there are cost- effective conservation measures that can be taken other than at-sea bycatch reduction devices and that these can have higher marginal biological and economic effectiveness than simple continued emphasis on steadily increasing bycatch reduction through conventional measures (with debatable efficiency due in part to diminishing returns).
Many questions arise about the best way to organize bycatch-saving technical change, inter alia: (i) the nature of public-private partnerships; (ii) the type and amount of research and development (R&D); (iii) financing methods in taxes and kind; (iv) who pays?; (v) length of R&D projects, (vi) and role and form of subsidies, etc.
The meeting will address many of these questions, but will focus on: (i) Endangered, vulnerable and other emblematic species bycatch in fisheries for highly migratory species; (ii) Economic and financial instruments to efficiently strengthen by-catch reduction policies; (iii) A broader-based ecosystem approach to by-catch reduction; and (iv) Concrete biodiversity mitigation strategies for the aforementioned bycatch species.  


*Notes:*
Long report from a workshop on investigating ways to better reduce ecosystem-level impacts of fisheries (PS and LL) bycatch on marine megafauna in large pelagic ecosystems and fisheries. Conventional bycatch reduction methods are not cost effective and don't consider ways to mitigate impacts at the ecosystem level. Incentive-based bycatch reduction practices including taxes, property rights, taxes, credit schemes or insurance have received insufficient attention and may be more effective and lead to least-cost conservation.  The report covers  conservatory mitigation approaches (including economic incentives and policy instruments). **Most important thing to note is that it discusses a Coaesian bargan between LL and PS to reduce bigeye catch (pgs. 45-46) as example of when PES can create incentive to sucessfully address incidental catches in eastern Pacific**: "The distribution and nature of costs and benefits of conservation contributes to a misalignment of incentives for conservation and recovery.Payments for ecosystem services (PES) directly create economic incentives and can address incidental catches in two broad circumstances: (1) finfish catch that may or may not be marketed and that can include “bycatch” or (2) incidental takes of sea turtles, sharks, sea birds, marine mammals, and other marine megafauna in which PES are part of biodiversity mitigation".

PES from LL to PS to reduce BET catch would help avoid issues associated with creating and allocating property rights and  high costs of observer and compliance/enforcement, and would be voluntary bargaining between the 2 parties. He suggests arrangement could include observable and verified reductions in landings (processor receipts checked against landings) OR payments could be arranged based on increased bigeye stock and TAC (payments would have to lag catches). A voluntary arrangement like this would shift burden of compliance and enforcement from regional management bodies to private sector. Internal coordination and asymmetric information problems would make this solution complicated.
 
 Discusses examples where this type (but not exact) solution has been applied: 
 * U.S. tuna fleet revenue sharing arrangement with the FFA- progressively sliding scale for skipjack tuna prices above a base level as incentive to cap fishing capacity
 * AK Pollock fishery cooperates in managing share of Pollock TAC
 * North Pacific Fur Seal Treaty- 2 nations stopped pelagic sealing fishing and profits were shared between pelagic sealing nations and nations with land-based harvesting
 
 This type of voluntary arrangement requires 3 conditions to be successful: (1)strong participation incentives, (2) clearly identified standards for behavior or performance, and (3) sufficient monitoring. Potential for strong free riding incentives exist between ll and ps which will reduce policy effectiveness. Important to make sure ps that don't reduce bet catch don't receive any payments. Also important to make sure all longliners pay for benefits of increased catches. Sharing individual vessel catch records could result in peer pressure to decrease free riding. Incentives exist to eliminate PS BET discards or misreporting since this would have a negative impact on the stock and lower PES, but there could still be a problem since vessels can free ride on other vessels reductions.  Onshore MCS and payments for landings not catches help contain asymmetric information issues with contracts.
 
Lower FAD fishing will create external benefits by the increased provision of the biodiversity public good. Asian LL will lower bycatch with less FAD fishing. Consumers will enjoy nonmarket benefits from increased biodiversity. PS will benefit in product markets from NGOs and consumers to reduce FAD caught skj, creating a potential for bundling where PES for reduced bycatch of other species (I think we discussed this idea at some point). Report discusses bundling examples such as protection of rainforests to sequester carbon through REDD payments also conserves biodiversity and other rain forest ecosystem services. Also talks about stacking- ex. if fishers reduce turtle bycatch they may also be reducing bycatch for sharks and should receive payments for both.

Discusses the potential of transferable bet rights in ps/ll fishery that would allow bet rights to rest in the hands of the highest valued vessels and gear type with gains from trade for both gear types. However, this would require observers (high cost) and  establishing this system would be expensive to establish and operation and would require RFMO involvement. These costs must be considered against rent gains.

Report also discusses taxes as a policy instrument for creating economic incentive. Taxes or limits on FADS as 2 effects on incentives: 1. reduces overall effort by raising costs, which reduces catch of non-target species 2. creates incentive to shift to unassociated sets. An example of indirect tax is full retention of bycatch to incentivize reduced behavior bc bycatch takes up space on the boat and there are costs associated with process and marketing.  


**Local, regional and global markets: what drives the tuna fisheries?**
[@Guillotreau2017]

*Abstract:*
Tuna products are amongst the most popular seafoods in the world and widely traded across the globe. Their global trade developed at a very early stage in the growth and development of tuna fisheries. In this article, recent evolutions of tuna markets in terms of products (for both sashimi and cannery-grade tuna products), market structures, and trade are introduced followed by a comprehensive study of global integration through price linkages. Most studies show a high degree of market integration and compe- tition through prices at the world-wide level. Finally, we introduce some original results about the relation- ship between catches and prices (estimated coefficients of demand elasticity and flexibility), and provide answers to a few key questions for tuna fisheries and markets, including: How do consumers respond to price changes? Are fish price changes fully transmitted to consumers? Is there any economic incentive for fishers to comply with reduced catch quotas? Do fishers target particular tuna species according to the relative price of tuna species?

*Notes:*
Tuna prices on the sashimi market represent 5x the price levels reached by cannery grade tuna- both price per fish and price per pound of fish is higher for fish landed in LL fishery. Juvenile BET caught in PS are an example of an asymmetric or unilateral externality where PS impart an adverse impact that is not captured by market prices and is uncompensated by LL vessels. Current management in EPO doesn't not maximize the total value of EPO catches. A mechanism like Coaesian bargaining that would enable transfer or a common catch or effort quota across vessels would increase efficiency. In summary, a 1% annual reduction in purse-seine effort on tunas associated with floating objects (roughly 84 sets), would imply a 300.6 mt reduction in the catch of juvenile bigeye tuna, and maintain the spawning biomass ratio of the bigeye tuna resulting in an increase in longline catch of 1170 mt. This would increase the total catch value by $10.74 Million US dollars. An equitable method is needed to allocate effort among the different fleets and member nations and to allow transfers of effort to enable gains in economic efficiency.

Method could be property rights system that provides a transferable quota for each fleet or nation based on some equitable scheme. A compensation system could be used to pay the PS fleet to reduce fishing effort through the market and quota trade as ll catching higher value bet paid PS for catch rights. BET quota within LL would also migrate to highest value in LL fleet. Another method could just be Coaseian bargaining between ll and PS vessels but verifying longer term population impact and compliance would be difficult. MSY could also rise with shift in F on age-structure creating a win-win situation for both fleets. 

Important to consider the impact incentives and market integration when setting TACs. Revenue increases may occur when TAC is reduced for conservation when prices that are linked to quantity (price increases more than quantity falls). In addition if TACs are reduced and allocated correctly, costs would be expected to decline with reduced effort, which would contribute to increased profits. This situation would create incentives for fishers to collectively accept conservation measures leading to win-win for conservation and fishers. Discusses price elasticities for skj and bet sashimi, fresh bet has larger price flexibility coefficient. 'TAC reduction operated uniformly at the world-wide level (e.g. all purse-seine fleets reducing by 10% their catch levels) would leave the fishers’ revenue unchanged because of the proportional (i.e., 10%) rise in prices.'  


**A Global Review of Incentive Payments for Sea Turtle Conservation**
[@Ferraro2009]

*Abstract:*
Performance payment conservation approaches are based on a willing buyer–willing seller model. Sellers deliver conservation outcomes in exchange for a negotiated payment in cash or in kind. The use of performance payments to achieve conservation outcomes is increasingly being used as an alternative to traditional regulatory and development-based approaches in low- income nations. Although payments are increasingly common in terrestrial species and ecosystem conservation initiatives, they are rare in marine conservation efforts such as sea turtle protection. This paper describes sea turtle incentive payment initiatives taking place around the world, most of which are found in projects focusing on nesting beach protection. We find that many of these initiatives have achieved substantial results for a very low annual cost. The potential for expanding payment incentive schemes beyond nest protection to reduce bycatch and hunting pressures on juvenile and adult turtles is unknown but should be further explored.  

*Notes:*
Direct payment conservation approaches are common in terrestrial and ecosystem conservation initiatives but rare in marine conservation efforts. Paper describes sea turtle incentive payment initiatives taking place around the world- where payments are specifically tied to conservation outcomes. Very successful programs where patrollers are paid to id a turtle next and again when the nest hatches successfully.  in Kenya, where monitors are paid once when they report the nest and paid again when the next hatches successfully. Overall programs are successful. Also describes program where fishers are paid to release and tag live turtles from fishing gear. Payment schemes are as (or more) effective as regulatory approaches but cost much less. Concludes that success is tied to ability of citizens to impose and enforce property rights, and how directly linked payment is to environmental outcome.  


**Papers from Conservation Letters:**

**Bioeconomic losses from overharvesting tuna**
[@Kompas2010]

*Abstract:*
Stochastic dynamic programming is used to model the world's largest fishery—tunas of the western and central Pacific—and to show that adopting a biomass target that maximizes the discounted economic profits (BMEY) from harvesting would result in larger stocks compared to de facto biological targets, and also lower catches relative to business as usual. This result is obtained for the three major tuna species, including skipjack tuna, which is not currently considered to be overfished biologically. Gains from larger tuna stocks are shown to exceed US$ 3 billion and increase the likelihood of stock rebuilding as some of these higher profits could be used to compensate fishers and countries for transitional losses to higher biomass levels. Adopting a dynamic BMEY target thus offers a potential “win-win”—better conservation outcomes with larger fish stocks and higher economic profits.  


*Notes:*
The results provide both an economic and a biological justification for reducing current fishing effort and increasing biomass levels of all tunas (including skipjack tuna) in the world's largest fishery. Higher future profits can be used to compensate fishers fully for initially lower harvests and net returns as stocks transition to higher biomass. Profits could also be used to finance transfers of funds to some countries, or possibly via the transfer of annual harvest allocations (Chand et al. 2003; Munro & van Houtte 2004; Grafton et al. 2010) to help ensure support for lower overall catches. A continuation of business-as-usual in the tuna fisheries will not only generate much lower profits relative to a dynamic maximum economic yield target, but will also jeopardize the conservation of yellowfin and bigeye tuna stocks.  


**Paying for an Endangered Predator Leads to Population Recovery** 
[@Persson2015]

*Abstract:*
Keeping viable predator populations on a human-dominated planet will require innovative approaches that promote local coexistence with human activities. Conservation performance payments, which are linked specifically to the production of a desired environmental output, have received increasing attention but their effectiveness in predator conservation remains undocumented. Here, we show that paying Sámi reindeer herders for wolverine (*Gulo gulo*) reproductions has been instrumental in the recovery of wolverines in Sweden. Adult female wolverines were significantly less exposed to illegal killing and this allowed the population to more than double in a decade. We argue that this program provides protection for adult female wolverines through a combination of direct monetary value and indirect protection because of monitoring activities. The program's success, even in a system where livestock is the main prey for the predator, reveals an exceptional potential for future implementations in large carnivore conservation.  


*Notes:*
Conservation of large carnivores in the past has relied on two strategies: (1) legal protection (2) prevention and compensation for depredation to local farmers negatively affected by carnivores. However, these approaches are inherently limited because they don't provide incentives for human-carnivore coexistence. Illegal killing of carnivores is still largest source of mortality. Conservation Performance Payments (CPP) have become popular, but there has been no evaluation of effectiveness so it has not been widely adopted. Best example is wolverine in Swedish reindeer husbandry area that is publicly funded. Farmers are paid by number of wolverine reproductions in their districts regardless of predation levels. Payments used to cover costs of predation on reindeer and simultaneously accounts for conservation value of wolverines.  


This study investigates whether CPP has had positive impact on # of female reproducing wolverines using long-term data from population monitoring programs. Reproduction increased significantly after 5 years of implementation of CPP. No poaching at dens has been recorded since introduction of program, this activity did occur frequently before 1996. Population monitoring occurred during season when conditions are most favorable for poaching acting as a temporal deterrent. Increased interactions between 'buyer' and 'seller' (herders and managers) has likely improved trust and understanding between groups. This study was not able to disentangle the indirect protective effect of monitoring and the direct effect of monetary compensation.

Study highlights importance of choosing efficient indicator for CPP. Also important that payment is made regardless of actual losses to herders, efficient herding is still beneficial.  


**Carbon Payments as a Safeguard for Threatened Tropical Mammals** 
[@Venter2009]

*Abstract:*
One reason for the rapid loss of species-rich tropical forests is the high opportunity costs of forest protection. In Kalimantan (Indonesian Borneo), the expansion of high-revenue oil palm (Elaeis guineensis) plantations currently threatens 3.3 million ha of forest. We estimate that payments for Reduced Emissions from Deforestation and forest Degradation (REDD) could offset the costs of stopping this deforestation at carbon prices of US$10–33 per tonne of CO2, or $2–16 per tonne if forest conservation targets only cost-efficient areas. Forty globally threatened mammals are found within these planned plantations, including the Bornean orangutan (*Pongo pygmaeus*) and Borneo pygmy elephant (Elephas maximus borneensis). Cost-efficient areas for emissions reductions also contain higher-than-average numbers of threatened mammals, indicating that there may be synergies between mitigating climate change and conserving biodiversity. While many policy and implementation issues need clarification, our economic assessment suggests that REDD could offer a financially realistic lifeline for Kalimantan's threatened mammals if it is included in future climate agreement.  

*Notes:*
There are insufficient funds to protect Indonesia's forests from conservation to production landscapes. REDD is a financial incentive for developing countries that voluntarily reduce deforestation rates and carbon emissions below a reference level. Compensation may come through a grant funding mechanism or through the sale of carbon credits on international carbon markets. This paper determines if a REDD mechanism has financial capacity to stap planned deforestation for oil palm in Kalimantan (Indonesia) and measures biodiversity outcomes of doing so. First, they look at how planned oil palm plantations will threaten forest biodiversity by focusing on IUCN vulnerable and endangered species. They used two scenarios (high and low) for carbon prices and palm development.

There was considerable spatial variation in the cost of carbon, so targeting low-cost areas could help reduce the cost of carbon. On the 50% of plantations where carbon was the cheapest, there were on average 2x the number of threatened mammals per km^2^. They found stopping deforestation would cost between $10 and $33 per tonne of carbon. REDD could only compete with oil palm in carbon-rich peat forests. REDD investments should focus on areas where emission reductions are cheapest.  


## References